"""empty message

Revision ID: 336213c77846
Revises: 86996ab4c49e
Create Date: 2024-03-23 11:11:44.508691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336213c77846'
down_revision = '86996ab4c49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=250),
               existing_nullable=False)
        batch_op.drop_constraint('planets_name_key', type_='unique')
        batch_op.drop_constraint('planets_population_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_population_key', ['population'])
        batch_op.create_unique_constraint('planets_name_key', ['name'])
        batch_op.alter_column('name',
               existing_type=sa.String(length=250),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
