"""empty message

Revision ID: 4471b0be351c
Revises: 72c5a4dbd4b9
Create Date: 2024-03-25 20:28:39.904227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4471b0be351c'
down_revision = '72c5a4dbd4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_birth_year_key', type_='unique')
        batch_op.drop_constraint('character_eye_color_key', type_='unique')
        batch_op.drop_constraint('character_gender_key', type_='unique')
        batch_op.drop_constraint('character_hair_color_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_hair_color_key', ['hair_color'])
        batch_op.create_unique_constraint('character_gender_key', ['gender'])
        batch_op.create_unique_constraint('character_eye_color_key', ['eye_color'])
        batch_op.create_unique_constraint('character_birth_year_key', ['birth_year'])

    # ### end Alembic commands ###
