"""empty message

Revision ID: 72c5a4dbd4b9
Revises: 629234a5d3cf
Create Date: 2024-03-25 20:25:25.120526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c5a4dbd4b9'
down_revision = '629234a5d3cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_birth_year_key', type_='unique')
        batch_op.drop_constraint('planets_climate_key', type_='unique')
        batch_op.drop_constraint('planets_diametro_key', type_='unique')
        batch_op.drop_constraint('planets_orbital_period_key', type_='unique')
        batch_op.drop_constraint('planets_rotation_period_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.create_unique_constraint('planets_rotation_period_key', ['rotation_period'])
        batch_op.create_unique_constraint('planets_orbital_period_key', ['orbital_period'])
        batch_op.create_unique_constraint('planets_diametro_key', ['diametro'])
        batch_op.create_unique_constraint('planets_climate_key', ['climate'])
        batch_op.create_unique_constraint('planets_birth_year_key', ['birth_year'])

    # ### end Alembic commands ###
