"""empty message

Revision ID: 86996ab4c49e
Revises: efe94d5c1415
Create Date: 2024-03-21 20:53:39.362567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86996ab4c49e'
down_revision = 'efe94d5c1415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('age', sa.String(length=250), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('age')
        batch_op.drop_column('userName')

    # ### end Alembic commands ###
