"""empty message

Revision ID: cbcdf14fdd16
Revises: 336213c77846
Create Date: 2024-03-23 11:15:30.402176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbcdf14fdd16'
down_revision = '336213c77846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
